# Generated by Django 5.2.6 on 2025-10-23 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.EmailField(max_length=100, unique=True, verbose_name='ログインID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('parent_name', models.CharField(max_length=100, verbose_name='保護者氏名')),
                ('child_name', models.CharField(max_length=100, verbose_name='子ども氏名')),
                ('child_name_kana', models.CharField(max_length=100, verbose_name='子ども氏名（かな）')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10, verbose_name='性別')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='学校名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '生徒',
                'verbose_name_plural': '生徒一覧',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.EmailField(max_length=100, unique=True, verbose_name='ログインID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='氏名（かな）')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10, verbose_name='性別')),
                ('permission_level', models.CharField(choices=[('一般講師', '一般講師'), ('主任講師', '主任講師'), ('管理者', '管理者')], max_length=10, verbose_name='権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '講師',
                'verbose_name_plural': '講師一覧',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='授業日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('status', models.CharField(choices=[('予定', '予定'), ('出席', '出席'), ('欠席', '欠席'), ('振替', '振替'), ('中止', '中止')], default='予定', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.student', verbose_name='生徒')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.teacher', verbose_name='担当講師')),
            ],
            options={
                'verbose_name': '授業スケジュール',
                'verbose_name_plural': '授業スケジュール一覧',
                'db_table': 'schedule',
            },
        ),
    ]
