# Generated by Django 5.2.7 on 2026-01-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.EmailField(max_length=100, unique=True, verbose_name='ログインID(メールアドレス)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QRコード画像')),
                ('user_type', models.CharField(default='parent', max_length=10, verbose_name='ユーザータイプ')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('name', models.CharField(max_length=100, verbose_name='親氏名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='teacher', max_length=10, verbose_name='ユーザータイプ')),
                ('login_id', models.EmailField(max_length=100, unique=True, verbose_name='ログインID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='氏名（かな）')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10, verbose_name='性別')),
                ('permission_level', models.CharField(choices=[('一般講師', '一般講師'), ('主任講師', '主任講師'), ('管理者', '管理者')], max_length=10, verbose_name='権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '講師',
                'verbose_name_plural': '講師一覧',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='時間帯名')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='student', max_length=10, verbose_name='ユーザータイプ')),
                ('child_name', models.CharField(max_length=100, verbose_name='子ども氏名')),
                ('child_name_kana', models.CharField(max_length=100, verbose_name='子ども氏名（かな）')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10, verbose_name='性別')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='学校名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parent')),
            ],
            options={
                'verbose_name': '生徒',
                'verbose_name_plural': '生徒一覧',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='app.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': '生徒通知',
                'verbose_name_plural': '生徒通知一覧',
                'db_table': 'student_notices',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='授業日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('status', models.CharField(choices=[('予定', '予定'), ('出席', '出席'), ('欠席', '欠席'), ('振替', '振替'), ('中止', '中止')], default='予定', max_length=10, verbose_name='ステータス')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='振替元日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('students', models.ManyToManyField(related_name='schedules', to='app.student', verbose_name='生徒（複数）')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.teacher', verbose_name='担当講師')),
            ],
            options={
                'verbose_name': '授業スケジュール',
                'verbose_name_plural': '授業スケジュール一覧',
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.parent')),
                ('parent_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.parent')),
                ('teacher_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.teacher')),
                ('teacher_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', '出席'), ('absent', '欠席')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.timeslot', verbose_name='時間帯')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日'), ('Sun', '日曜日')], max_length=3, verbose_name='出席曜日')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='app.student', verbose_name='生徒')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.timeslot', verbose_name='時間帯')),
            ],
            options={
                'unique_together': {('student', 'day_of_week')},
            },
        ),
    ]
