# Generated by Django 5.2.7 on 2026-02-03 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日'), ('Sun', '日曜日')], max_length=3, verbose_name='担当曜日')),
                ('is_primary', models.BooleanField(default=True, verbose_name='主担当')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='app.teacher', verbose_name='講師')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.timeslot', verbose_name='時間帯')),
            ],
            options={
                'unique_together': {('teacher', 'day_of_week', 'time_slot')},
            },
        ),
    ]
