# Generated by Django 5.2.7 on 2025-11-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.EmailField(max_length=100, unique=True, verbose_name='ログインID(メールアドレス)')),
                ('user_type', models.CharField(default='parent', max_length=10, verbose_name='ユーザータイプ')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('name', models.CharField(max_length=100, verbose_name='親氏名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(default='student', max_length=10, verbose_name='ユーザータイプ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_type',
            field=models.CharField(default='teacher', max_length=10, verbose_name='ユーザータイプ'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.student')),
                ('student_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.student')),
                ('teacher_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.teacher')),
                ('teacher_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parent'),
        ),
    ]
