# Generated by Django 5.2.7 on 2026-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacherattendancerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='システムメッセージ'),
        ),
    ]
