# Generated by Django 5.2.7 on 2026-01-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentnotice',
            options={},
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notice_files/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='掲載期限'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='重要'),
        ),
    ]
