# Generated by Django 5.2.7 on 2026-01-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentnotice_options_studentnotice_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読'),
        ),
    ]
